### ISSUE TITLE
dynamic debuginfo URL for downstream

### ISSUE THREAD

**Issue by shenjoon** [clearlinux/clr-debug-info#3]
It will be great to have this not hardcoded and to be able to dynamically change the URL as needed to cater for downstream images that contains a different set of debuginfo.

`
char *urls[2] = { "https://cdn.download.clearlinux.org/debuginfo/",
                  "https://cdn-alt.download.clearlinux.org/debuginfo/" };`

**Comment by phmccarty** [comment]
@shenjoon How would you like to see this implemented? We could look into adding option parsing, or reading a conf file containing the URLs, or both.

**Comment by phmccarty** [comment]
Or perhaps we need not bother with runtime configuration at all and add configure-time options instead.

**Comment by shenjoon** [comment]
Since this hardcode url variable was only used in 1 function, I was thinking if the capability could search for an existence of a file that overwrites this variable say "debuginfo.ini", then it would overwrite this variable with the new link. Will this work?

**Comment by yewwayne** [comment]
To offer another suggestion: could the url(s) be passed into the daemon via an environment variable? We could define it in clr_debug_daemon.service. Provided we won't be adding many more configuration options going forward, this removes need for a config parser in the codebase while still allowing runtime configuration.
